### PR TITLE
Add compose-macos-theme

### PR DESCRIPTION
**Pull request by Chozzle**
I've created this library https://github.com/Chozzle/compose-macos-theme
It could be very useful for anyone wanting to write a Multiplatform app UI, that appears native.

### CODE REVIEW

**Comment by AAkira** [comment]
Please add two spaces after the description for a new line.

**Comment by AAkira** [comment]
And please add it after `kotlin-material-ui`.

**Comment by Chozzle** [comment]
Done!

**Comment by AAkira** [comment]
Thank you!! 😊

**Pull request merged**
