### PR TITLE
Add Ivy DI

### PR DESCRIPTION
**Pull request by ILIYANGERMANOV**
# Ivy DI

https://github.com/Ivy-Apps/di

---

- [x] Confirmed that two spaces were added at the end of the description to break a new line.

### CODE REVIEW

**Comment by ILIYANGERMANOV** [comment]
@AAkira can you please review? 👀

**Comment by TheArchitect123** [comment]
Is this repo even being maintained anymore?
I don't think so. I've waited over a month for my PR to be approved, and nothing.

https://github.com/AAkira/Kotlin-Multiplatform-Libraries/pull/231

@AAkira @ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
cc @soleil-colza

**Review by soleil-colza — APPROVED** [review]

**Comment by soleil-colza** [comment]
> cc @soleil-colza
Your contribution is appreciated!👍🏻

**Comment by ILIYANGERMANOV** [comment]
Thank you! ✨️ Keep up the great work on the libraries catalog

**Comment by TheArchitect123** [comment]
@soleil-colza 
Can you approve my pull request too please?
😃
222 stars and climbing on my repo.

https://github.com/AAkira/Kotlin-Multiplatform-Libraries/pull/231

**Comment by soleil-colza** [comment]
> @soleil-colza 
> Can you approve my pull request too please?
> 😃
> 222 stars and climbing on my repo.
> 
> https://github.com/AAkira/Kotlin-Multiplatform-Libraries/pull/231

I'll look into it! One sec 🙆‍♀️

**Pull request merged**
