### PR TITLE
suparnatural-fs

### PR DESCRIPTION
**Pull request by suparngp**
This package provides APIs for common use cases to interact with the file system on iOS and Android.

Highlights

- Cross platform Thread-Safe API to read/write/copy/move and manage files on both iOS and Android
- Support for UTF-8, Ascii and Base64 formats while reading and writing.

Link to docs
https://suparngp.github.io/kotlin-multiplatform-projects/fs/docs/suparnatural-fs/index.html

Link to source
https://github.com/suparngp/kotlin-multiplatform-projects/tree/master/fs

Link to License (MIT)
https://github.com/suparngp/kotlin-multiplatform-projects/blob/master/LICENSE

Link to artifacts (Bintray)
https://dl.bintray.com/suparnatural/kotlin-multiplatform/suparnatural-kotlin-multiplatform/

### CODE REVIEW

**Comment by AAkira** [comment]
@suparngp 

Hello, Is it an open source project?
I would like to add an open source project to this repository.

And I can't use this library.
Please check it again.

**Comment by suparngp** [comment]
Yes, the artifact is published publicly on the bintray. You can check a list of all the artifacts here.
https://dl.bintray.com/suparnatural/kotlin-multiplatform/suparnatural-kotlin-multiplatform/

By any chance, did you miss adding the repository url as it is not available on maven central yet?

**Comment by suparngp** [comment]
I am not really sure why you weren't able to access the artifacts, source code, license for these projects. I have updated the each PR's description with the links to all of the above.

**Comment by AAkira** [comment]
`implementation 'suparnatural-kotlin-multiplatform:android-ios:1.0.5'` is wrong.
I think 
`implementation 'suparnatural-kotlin-multiplatform:fs-android:1.0.5'`

**Comment by suparngp** [comment]
Thank You, Fixed the read me.

**Pull request merged**
