### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by toth-istvan-zoltan**

### CODE REVIEW

**Comment by AAkira** [comment]
What is this library?
I don't think it's the right position to insert it.

It should be inserted at the end of 
https://github.com/AAkira/Kotlin-Multiplatform-Libraries#build--development-tools
or 
https://github.com/AAkira/Kotlin-Multiplatform-Libraries#architecture

Is this correct?

**Comment by toth-istvan-zoltan** [comment]
It is a library to develop full-stack applications.

I tried to find a good place in the list for it, but couldn't. It is a unique at the moment, and that's the whole point.

A month or so ago I've actually tried for days to write down what this library does and failed miserably. Shortly put:

Zakadabar * (Browser + Android + Ktor + SQL) = Working Application

About a year ago I met Kotlin multiplatform and thought: this is great, I can write everything in Kotlin, no need for Javascript, no need for Java EE craziness. I can put my data model in commonMain and happily use it form everywhere. Simple, effective, Kotlin.

Here comes the surprise: there is no multiplatform library that is Kotlin-only and lets you do this properly. Kvision comes close but it takes a different approach.

As of now Kotlin MPP says: use this dependency from Java, use that dependency from Javascript. Use react, use spring.

I don't want to use react, I don't want to use spring. I used both and was unhappy. I want to use Kotlin.

So, I've written a Kotlin MPP library that independent from Javascript and Java as much as possible. (Took a year of work.)

This library lets you code an actual, working, meaningful business application, with enterprise grade features, in less than a day. Using only Kotlin. Server and client, works out-of-the-box.

**Comment by AAkira** [comment]
Thanks for the detailed explanation.
This one seems similar to [KaMPKit](https://github.com/touchlab/KaMPKit).

Could you insert it at the end of Build & Development Tools?

I'll add more categories when more similar libraries are registered.

**Comment by toth-istvan-zoltan** [comment]
I did insert it under Build & Development tools. It doesn't really belongs there, but it is better to be in the wrong place than not being in the list at all. 

I had the same problem on Kotlin discussion forums. I could put it under one category only, while it clearly belongs to multiple categories.

Anyway, thank you for your work maintaining this list.

**Comment by AAkira** [comment]
Thank you!

**Pull request merged**
