### PR TITLE
Add library `secure-random`

### PR DESCRIPTION
**Pull request by 05nelsonm**
# secure-random

* A cryptographically secure random number generator, `SecureRandom`

[secure-random](https://github.com/05nelsonm/secure-random)

---

- [x] Confirmed that two spaces were added at the end of the description to break a new line.

### CODE REVIEW

**Comment by 05nelsonm** [comment]
Heyo! Wanted to ask your thoughts on adding some sort of additional badge to indicate support for more than just `linuxX64`. There's a whole host of projects that only have x64 support, and others that have full support for Linux.

 - `linuxArm32Hfp`
 - `linuxArm64`
 - `linuxMips32`
 - `linuxMipsel32`

Maybe something like

![badge-linux-arm]
![badge-linux-mips]

```
[badge-linux-arm]: http://img.shields.io/badge/support-[LinuxArm]-2D3F6C.svg?style=flat
[badge-linux-mips]: http://img.shields.io/badge/support-[LinuxMIPS]-2D3F6C.svg?style=flat
```

[badge-linux-arm]: http://img.shields.io/badge/support-[LinuxArm]-2D3F6C.svg?style=flat
[badge-linux-mips]: http://img.shields.io/badge/support-[LinuxMIPS]-2D3F6C.svg?style=flat

**Comment by AAkira** [comment]
@05nelsonm 

Thanks for the suggestion.
You may add tags there.

Sorry for the late reply.

**Comment by 05nelsonm** [comment]
> @05nelsonm
> 
> Thanks for the suggestion. You may add tags there.
> 
> Sorry for the late reply.

Heyo, no worries. I don't even think they're necessary anymore, as those targets are being deprecated as of `1.8.20`

**Comment by 05nelsonm** [comment]
Also, will be closing this PR as I've moved the library to the [KotlinCrypto](https://github.com/KotlinCrypto) organization. Will create another one at a later date with more of those libs that I'm working on over there.

**Comment by AAkira** [comment]
Thank you!

**Pull request closed without merging**
